---
title: 'Assignment #5'
author: "Richard Viebrock"
date: "11/27/2019"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}

# ------------------------
# Attach Relevant Packages
# ------------------------

library(tidyverse)
library(janitor)
library(directlabels)
library(DT)
library(kableExtra)
library(ggbeeswarm)
library(car)

```

```{r}

# --------------------------------
# Read in data and filter for DITE 
# --------------------------------

mack_creek <- read_csv("mack_creek_vertebrates.csv") %>% 
  clean_names() %>% 
  filter(species == "DITE")

```

```{r}

# --------------------------------
# Results A: Create DF for salamander count graph
# --------------------------------

mack_creek_count <- mack_creek %>% 
  select(year, section) %>% 
  filter(section %in% c("OG", "CC")) %>% 
  group_by(year, section) %>% 
  summarize(count = n())

# -------------------------------------------
# Use ggplot to create salamander count graph
# -------------------------------------------

ggplot(data = mack_creek_count, aes(x = year, y = count, group = section))+
  geom_line(aes(color = section), show.legend = FALSE)+
  geom_point(color = "gray50")+
  geom_dl(aes(label = section, color = section), method = list(dl.combine("last.points"), cex = 0.85))+
  scale_x_continuous(expand = c(0, 0),
                   limits = c(1993, 2019.5),
                   breaks = seq(1993, 2018, by = 5))+
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 800),
                     breaks = seq(0, 800, by = 200))+
  labs(x = "Year",
       y = "Count",
       title = "Salamander Counts by Section: 1993 - 2017")+
  theme_light()

```

```{r}

# ---------------------------------------------------------------------
# Results B: Create DF for table (channel classification & forest type)
# ---------------------------------------------------------------------

mack_c_table <- mack_creek %>% 
  filter(section %in% c("OG", "CC")) %>% 
  mutate(section_name = if_else(section == "CC", "Clear Cut", "Old Growth")) %>% 
  select(year, section_name, unittype) %>%
  filter(year == 2017,
         unittype %in% c("C", "P", "SC")) %>% 
  group_by(section_name, unittype) %>% 
  summarize(count = n()) %>% 
  pivot_wider(names_from = unittype, values_from = count) %>% 
  rename(Cascades = "C",
         Pool = "P",
         "Side Channel" = "SC",
         Section = "section_name")

mack_c_props <- mack_c_table %>% 
  adorn_percentages(denominator = "row") %>% 
  adorn_pct_formatting(digits = 1) %>% 
  adorn_ns(position = "front")

# ------------------------------------
# Create contingency table using kable
# ------------------------------------

kable(mack_c_props) %>% 
  kable_styling()

```

```{r}

# ----------------------------------------------------
# Results C: Use chi-squared to determine independence
# ----------------------------------------------------

chi_mack <- mack_c_table %>%
  ungroup() %>% 
  select(-Section)

chi_mack_test <- chisq.test(chi_mack)

chi_mack_test

```

```{r}

# ---------------------------------------------
# Results D: Create data frame to compare means
# ---------------------------------------------

mack_c_weights_graph <- mack_creek %>% 
  select("year", "section", "weight") %>% 
  filter(section %in% c("OG", "CC"),
         year == 2017)

mack_c_summary <- mack_c_weights_graph %>% 
  group_by(section) %>% 
  summarize(
    mean_weight = mean(weight, na.rm = TRUE),
    sd_weight = sd(weight, na.rm = TRUE))

# ---------------------------------------
# Use ggbeeswarm to visually compare means
# ---------------------------------------

ggplot()+
  geom_beeswarm(data = mack_c_weights_graph, 
                aes(x = section, y = weight),
                size = 1,
                alpha = 0.6,
                color = "dodgerblue") +
  geom_point(data = mack_c_summary,
             aes(x = section, y = mean_weight),
             color = "red",
             size = 2) +
  geom_errorbar(data = mack_c_summary,
                aes(x = section,
                    ymin = mean_weight - sd_weight,
                    ymax = mean_weight + sd_weight),
                width = 0.1,
                color = "red")+
  scale_x_discrete(labels = c("Clear Cut", "Old Growth"))+
  labs(x = "Section",
       y = "Weight",
       title = "2017 Means Comparison: Old Growth vs Clear Cut")

# Make sure that the beeswarm and the means are lined up appropriately
```

```{r}

# --------------------------------------------------
# Conduct a means comparison using a 2-sample t-test
# --------------------------------------------------

 mack_weights_cc <- mack_c_weights_graph %>% 
   filter(section == "CC") %>% 
   pull(weight)

 mack_weights_og <- mack_c_weights_graph %>% 
   filter(section == "OG") %>% 
   pull(weight)

 mack_means_comparison <- t.test(mack_weights_og, mack_weights_cc)
 mack_means_comparison

```

```{r}

# ---------------------------------------------------
# Results E: Create data frame to compare by unittype
# ---------------------------------------------------

 mack_pcs_weights <- mack_creek %>% 
   select("year", "unittype", "weight", "section") %>% 
   filter(unittype %in% c("C", "P", "SC"),
          year == 2017,
          section %in% c("CC", "OG"))
 
 mack_pcs_summary <- mack_pcs_weights %>% 
   group_by(unittype) %>% 
   summarize(
     mean_weight = mean(weight, na.rm = TRUE),
     sd_weight = sd(weight, na.rm = TRUE),
     sample_size = n(),
     se_weight = sd(weight, na.rm = TRUE) / sqrt(n()),
     var_weight = var(weight, na.rm = TRUE))

```

```{r}

# ------------------------------------
# Make a QQ plot to determine normalcy
# ------------------------------------

ggplot(data = mack_pcs_weights, aes(sample = weight))+
  geom_qq()+
  facet_wrap(~unittype)

ggplot(data = mack_pcs_weights, aes(x = weight))+
  geom_histogram()+
  facet_wrap(~unittype)

# ------------------------------------------------
# Conduct a Lavene's test to ensure equal variance
# ------------------------------------------------

leveneTest(weight ~ unittype, data = mack_pcs_weights)

# ----------------------------------------------------
# Conduct a chi-squared test to check for independence?
# ----------------------------------------------------

# chi_pcs_mack <- mack_pcs_weights %>%
# group_by(unittype) %>% 
#  summarize(weight = mean(weights))

```

```{r}

# -----------------------------------
# Make beeswarm plot to compare means
# -----------------------------------

ggplot()+
   geom_beeswarm(data = mack_pcs_weights,
                 aes(x = unittype, y = weight),
                 size = 1,
                 alpha = 0.6,
                 color = "dodgerblue") +
   geom_point(data = mack_pcs_summary,
              aes(x = unittype, y = mean_weight),
              color = "red",
              size = 2)+
   geom_errorbar(data = mack_pcs_summary,
                 aes(x = unittype,
                     ymin = mean_weight - sd_weight,
                     ymax = mean_weight + sd_weight),
                 width = 0.1,
                 color = "red") +
   scale_x_discrete(labels = c("Cascade", "Pool", "Side Channel"))

 # Make sure that data is lined up correctly so that you don't have a mean in the wrong place. If the mack_pcs_weights is in the same order as mack_pcs_summary, everything works

```

```{r}

# ----------------------------------------
# Conduct a one-way ANOVA to compare means
# ----------------------------------------

mack_aov <- aov(weight ~ unittype, data = mack_pcs_weights)
summary(mack_aov)

# ----------------------------------------
# Conduct Tukey's HSD for post-hoc testing
# ----------------------------------------

TukeyHSD(mack_aov)

```